Resources:
  CloudFrontOriginReqPolicy:
    Properties:
      OriginRequestPolicyConfig:
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - origin
            - access-control-request-headers
            - access-control-request-method
        Name: ToDoEVVCORSRequestPolicy
        QueryStringsConfig:
          QueryStringBehavior: none
    Type: AWS::CloudFront::OriginRequestPolicy
  CloudFrontResponseHeadersPolicy:
    Properties:
      ResponseHeadersPolicyConfig:
        CorsConfig:
          AccessControlAllowCredentials: false
          AccessControlAllowHeaders:
            Items:
              - '*'
          AccessControlAllowMethods:
            Items:
              - GET
              - OPTIONS
              - HEAD
          AccessControlAllowOrigins:
            Items:
              - https://todoevv.matthewsapps.com
          OriginOverride: false
        Name: ToDoEVVCORSEnabled
    Type: AWS::CloudFront::ResponseHeadersPolicy
  CloudfrontBucketAccessPolicy:
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity '
                  - !Ref 'CloudfrontOriginAccess'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'WebsiteBucket'
                - /*
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
  CloudfrontDistroCachePolicy:
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 3153600
        MinTTL: 86400
        Name: cloudfront-todoevv-resources-cache-policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
    Type: AWS::CloudFront::CachePolicy
  CloudfrontOriginAccess:
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: To Do EVV Cloudfront Origin Access
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  RecordSet:
    Properties:
      AliasTarget:
        DNSName: !GetAtt 'ResourcesCloudFrontDistro.DomainName'
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: matthewsapps.com.
      Name: todoevv.matthewsapps.com
      Type: A
    Type: AWS::Route53::RecordSet
  ResourcesCloudFrontDistro:
    Properties:
      DistributionConfig:
        Aliases:
          - todoevv.matthewsapps.com
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !Ref 'CloudfrontDistroCachePolicy'
          OriginRequestPolicyId: !Ref 'CloudFrontOriginReqPolicy'
          ResponseHeadersPolicyId: !Ref 'CloudFrontResponseHeadersPolicy'
          TargetOriginId: todoevv.matthewsapps.com
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          - DomainName: !Join
              - ''
              - - !Ref 'WebsiteBucket'
                - .s3.
                - !Ref 'AWS::Region'
                - .amazonaws.com
            Id: todoevv.matthewsapps.com
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - ''
                - - origin-access-identity/cloudfront/
                  - !Ref 'CloudfrontOriginAccess'
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:473590191074:certificate/0d37d917-f950-423c-8407-efd8450e790e
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
    Type: AWS::CloudFront::Distribution
  WebsiteBucket:
    Properties:
      BucketName: todoevv.matthewsapps.com
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
    Type: AWS::S3::Bucket
